version: '2'

services:
  webapp:
    build: .
    volumes:
      - ./site-code:/usr/src/app
    expose:
      - "8080"
    depends_on:
      - rediscache
    links:
      - rediscache:redis
    env_file:
      - ./.docker/webapp.env
    restart: "always"
  rediscache:
    image: redis:alpine
    expose:
      - "6379"
    restart: "always"
  lb:
    image: nginx
    links:
      - webapp
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    ports:
      - 80:80
    restart: "always"
    depends_on:
      - webapp