version: '2'

services:
  webapp:
    build: .
    volumes:
      - ./site-code:/usr/src/app
    ports:
      - "8080:8080"
    depends_on:
      - rediscache
    links:
      - rediscache:redis
      env_file:
      - ./.docker/webapp.env
  rediscache:
    container_name: rediscache
    image: redis
    expose:
      - "6379"